import React from 'react';
import type { LiveTimelineEvent, ToolCallEvent } from '../types';
import LoadingIndicator from './LoadingIndicator';

const UserAvatar: React.FC = () => (
    <div className="w-8 h-8 rounded-full bg-gray-300 dark:bg-gray-600 flex items-center justify-center overflow-hidden flex-shrink-0">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-600 dark:text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>
    </div>
);

const BotAvatar: React.FC = () => (
    <div className="w-8 h-8 rounded-full bg-teal-500 flex items-center justify-center overflow-hidden flex-shrink-0">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
    </div>
);


const ToolCallCard: React.FC<{ event: ToolCallEvent }> = ({ event }) => {
    const { call, status, result } = event;
    const isError = status === 'error';
    
    return (
        <div className={`ml-10 p-2 text-xs rounded-lg border ${isError ? 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-700' : 'bg-gray-100 dark:bg-gray-700 border-gray-200 dark:border-gray-600'}`}>
            <div className="flex items-center font-medium text-gray-700 dark:text-gray-300">
                {status === 'pending' && <LoadingIndicator className="h-3 w-3 mr-2" />}
                {status === 'success' && <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3 mr-2 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>}
                {status === 'error' && <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3 mr-2 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>}
                <span>Tool Call: <code className="font-mono">{call.name}</code></span>
            </div>
            {status !== 'pending' && (
                 <pre className="mt-2 p-1.5 bg-white dark:bg-gray-800 rounded text-xs overflow-x-auto">
                    <code>{typeof result === 'object' ? JSON.stringify(result, null, 2) : String(result)}</code>
                </pre>
            )}
        </div>
    );
};


export const LiveEventCard: React.FC<{ event: LiveTimelineEvent }> = ({ event }) => {
    switch (event.type) {
        case 'user_speech':
            return (
                <div className="flex items-start justify-end group">
                    <div className="p-3 text-sm bg-teal-600 text-white rounded-t-lg rounded-bl-lg max-w-md">
                        {event.text}
                    </div>
                    <div className="ml-2 flex-shrink-0"><UserAvatar /></div>
                </div>
            );

        case 'bot_speech':
            return (
                <div className="flex items-start group">
                    <div className="mr-2 flex-shrink-0"><BotAvatar /></div>
                    <div className="p-3 text-sm bg-white dark:bg-gray-700 rounded-t-lg rounded-br-lg max-w-md shadow-sm">
                        <p>{event.text}</p>
                        {event.imageUrl && <img src={event.imageUrl} alt="Generated by AI" className="mt-2 rounded-lg max-w-xs w-full" />}
                        {event.document && <a href={event.document.dataUrl} download={event.document.fileName} className="mt-2 block w-full text-center px-3 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 transition-colors">Download {event.document.fileName}</a>}
                    </div>
                </div>
            );

        case 'tool_call':
            return <ToolCallCard event={event} />;

        case 'user_action':
            return (
                 <div className="text-center my-2">
                    <div className="inline-flex items-center space-x-2 text-xs text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700 px-3 py-1 rounded-full">
                         <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>
                        <span>{event.description}</span>
                    </div>
                    {event.imageUrl && <img src={event.imageUrl} alt="User capture" className="mx-auto mt-2 w-24 h-auto rounded-md" />}
                </div>
            );
        
        case 'system_message':
             return (
                 <div className="text-center my-2">
                    <div className="inline-flex items-center space-x-2 text-xs text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700 px-3 py-1 rounded-full">
                         <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                        <span>{event.message}</span>
                    </div>
                </div>
            );
        default:
            return null;
    }
};
